name: 'issue2readme'
on:
  workflow_dispatch:
  issues:
    types: [milestoned]
    # types: [opened, edited]
#   issue_comment:
#     types: [created, edited]
concurrency:
  # just run one action at a time
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #  Check out the repository, so it can read the files it and do other operations
      - name: Generate README
        uses: bxb100/issueblog@main # Prefer to use the latest version
        with:
          # Define the README.md header content
          md_header: |
            ## 简介
            使用Github Issues写博客.[RSS Feed](https://raw.githubusercontent.com/cloudswave/blog/master/feed.xml)
            同步发布到[EthanZhu's Blog](https://cloudswave.github.io)
          blog_author: "EthanZhu"
          recent_title: "最近更新"
          top_title: "置顶"
          links_title: "链接"
